# Generated by Django 3.2.5 on 2022-04-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0002_device_own_by_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='IotDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=200, unique=True)),
                ('device_name', models.CharField(max_length=200)),
                ('device_type', models.CharField(max_length=200)),
                ('own_by_user', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
